'use client';

import { ArrowUpRight, ShieldCheck } from 'lucide-react';

export default function AboutPage() {
  return (
    <main className="detailPage">
      <nav className="detailNav shell"><a className="brand" href="/" onClick={(event) => { event.preventDefault(); window.location.assign('/'); }}><span>FC</span><strong>Franc Cadet</strong></a><div><a href="/" onClick={(event) => { event.preventDefault(); window.location.assign('/'); }}>Home</a><a className="active" href="/about" onClick={(event) => { event.preventDefault(); window.location.assign('/about'); }}>About</a><a href="/skills" onClick={(event) => { event.preventDefault(); window.location.assign('/skills'); }}>Skills</a><a href="https://www.linkedin.com/in/franc-cadet-7957441bb/" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={15} /></a></div></nav>
      <section className="detailHero shell"><p className="detailEyebrow">01 / ABOUT</p><h1>Built for the work<br />behind <em>secure systems.</em></h1><p className="detailLead">I am an Information Technology student at the University of Central Florida and a current SOC Analyst Intern at Leidos. I bring a security-first mindset to every system, ticket, and technical decision.</p></section>
      <section className="detailGrid shell"><article><span>NOW</span><h2>SOC Analyst Intern</h2><p>At Leidos, I review DoD intelligence for threats, support system hardening, and perform basic cyber analysis of potential events, vulnerabilities, risks, and threats.</p></article><article><span>BEFORE</span><h2>Help Desk Analyst</h2><p>At Cadet’s Solutions for the Body & Soul, I configured hardware and software for new employees, completed system maintenance, and supported updates and patch installations.</p></article><article><span>EDUCATION</span><h2>UCF & Valencia</h2><p>B.S. in Information Technology at UCF, expected May 2026. I also earned an A.A. from Valencia College, where I made the President’s List in Fall 2023.</p></article></section>
      <section className="detailBanner"><div className="shell"><ShieldCheck /><div><p>SECURITY-FOCUSED</p><h2>Systems should be reliable, resilient, and ready.</h2></div></div></section>
      <footer className="detailFooter shell"><a href="/skills" onClick={(event) => { event.preventDefault(); window.location.assign('/skills'); }}>Explore my skills <ArrowUpRight size={18} /></a><a href="/" onClick={(event) => { event.preventDefault(); window.location.assign('/'); }}>Back to home</a></footer>
      <style>{`.detailPage{min-height:100vh;background:var(--cream);color:var(--navy)}.detailNav{height:88px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #d9d4ca}.detailNav>div{display:flex;gap:25px;align-items:center;font-size:11px;font-weight:800;letter-spacing:.13em;text-transform:uppercase}.detailNav>div>a:not(:last-child).active{color:#a87b08;position:relative}.detailNav>div>a:not(:last-child).active:after{content:'';position:absolute;left:0;right:0;bottom:-12px;height:3px;background:var(--gold)}.detailNav>div>a:last-child{display:flex;gap:7px;align-items:center;border:1px solid #aab5bf;padding:12px 15px}.detailHero{padding:105px 0 85px}.detailEyebrow{font-size:11px;font-weight:800;letter-spacing:.2em;color:#9a792b}.detailHero h1{font:650 clamp(48px,7vw,92px)/.94 var(--font-display);letter-spacing:-.06em;margin:24px 0}.detailHero h1 em{font-style:normal;color:#bd8810}.detailLead{max-width:720px;font-size:20px;line-height:1.7;color:#4d5e70}.detailGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;padding-bottom:110px}.detailGrid article{padding:32px;background:#fff;border-top:4px solid var(--gold)}.detailGrid span{font-size:10px;letter-spacing:.18em;color:#a17d28;font-weight:800}.detailGrid h2{font:650 30px var(--font-display);margin:18px 0 12px}.detailGrid p{color:#59697a;line-height:1.7}.detailBanner{background:var(--navy);color:#fff}.detailBanner>div{display:flex;align-items:center;gap:24px;padding:55px 0}.detailBanner svg{color:var(--gold);width:50px;height:50px}.detailBanner p{font-size:10px;font-weight:800;letter-spacing:.18em;color:var(--gold)}.detailBanner h2{font:600 32px var(--font-display);margin:8px 0}.detailFooter{display:flex;justify-content:space-between;padding:40px 0;font-weight:800}.detailFooter a{display:flex;align-items:center;gap:9px}@media(max-width:700px){.detailNav{height:74px}.detailNav .brand strong{display:none}.detailNav>div{gap:15px;font-size:10px}.detailNav>div>a:last-child{display:none}.detailHero{padding:72px 0 60px}.detailLead{font-size:17px}.detailGrid{grid-template-columns:1fr;padding-bottom:70px}.detailFooter{font-size:13px}}`}</style>
    </main>
  );
}
