'use client';

import { ArrowUpRight, Award, MonitorCog, Network, ShieldCheck } from 'lucide-react';

const skillGroups = [
  { number: '01', title: 'Cyber Defense', icon: ShieldCheck, text: 'SOC analysis, system hardening, vulnerability assessment, risk analysis, threat awareness, Microsoft Defender, and firewalls.', tags: ['SOC ANALYSIS', 'DEFENDER', 'FIREWALLS'] },
  { number: '02', title: 'Networking', icon: Network, text: 'Local Area Network foundations, Wireshark-based traffic analysis, Active Directory, and an understanding of reliable connectivity.', tags: ['WIRESHARK', 'LAN', 'ACTIVE DIRECTORY'] },
  { number: '03', title: 'IT Support', icon: MonitorCog, text: 'Hardware assembly, Windows, Linux, macOS, employee setup, software configuration, system updates, and patching.', tags: ['WINDOWS', 'LINUX', 'MACOS', 'HARDWARE'] },
  { number: '04', title: 'Credentials', icon: Award, text: 'CompTIA Security+, CompTIA IT Fundamentals, active Secret clearance, and LSAMP STEM leadership participation.', tags: ['SECURITY+', 'ITF+', 'LSAMP'] },
];

export default function SkillsPage() {
  return (
    <main className="skillsPage">
      <nav className="detailNav shell"><a className="brand" href="/" onClick={(event) => { event.preventDefault(); window.location.assign('/'); }}><span>FC</span><strong>Franc Cadet</strong></a><div><a href="/" onClick={(event) => { event.preventDefault(); window.location.assign('/'); }}>Home</a><a href="/about" onClick={(event) => { event.preventDefault(); window.location.assign('/about'); }}>About</a><a className="active" href="/skills" onClick={(event) => { event.preventDefault(); window.location.assign('/skills'); }}>Skills</a><a href="https://www.linkedin.com/in/franc-cadet-7957441bb/" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={15} /></a></div></nav>
      <section className="detailHero shell"><p className="detailEyebrow">02 / SKILLS</p><h1>Technical curiosity,<br /><em>practical impact.</em></h1><p className="detailLead">A growing IT toolkit grounded in cybersecurity operations, networking, systems support, and continuous learning.</p></section>
      <section className="detailSkillGrid shell">{skillGroups.map(({ number, title, icon: Icon, text, tags }) => <article key={title}><span>{number}</span><div className="detailIcon"><Icon /></div><h2>{title}</h2><p>{text}</p><div>{tags.map(tag => <b key={tag}>{tag}</b>)}</div></article>)}</section>
      <footer className="detailFooter shell"><a href="/about" onClick={(event) => { event.preventDefault(); window.location.assign('/about'); }}>Read my background <ArrowUpRight size={18} /></a><a href="/" onClick={(event) => { event.preventDefault(); window.location.assign('/'); }}>Back to home</a></footer>
      <style>{`.skillsPage{min-height:100vh;background:var(--navy2);color:#fff}.detailNav{height:88px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid rgba(255,255,255,.16)}.detailNav>div{display:flex;gap:25px;align-items:center;font-size:11px;font-weight:800;letter-spacing:.13em;text-transform:uppercase}.detailNav>div>a:not(:last-child).active{color:var(--gold);position:relative}.detailNav>div>a:not(:last-child).active:after{content:'';position:absolute;left:0;right:0;bottom:-12px;height:3px;background:var(--gold)}.detailNav>div>a:last-child{display:flex;gap:7px;align-items:center;border:1px solid rgba(255,255,255,.35);padding:12px 15px}.detailHero{padding:105px 0 75px}.detailEyebrow{font-size:11px;font-weight:800;letter-spacing:.2em;color:var(--gold)}.detailHero h1{font:650 clamp(48px,7vw,92px)/.94 var(--font-display);letter-spacing:-.06em;margin:24px 0}.detailHero h1 em{font-style:normal;color:var(--gold)}.detailLead{max-width:720px;font-size:20px;line-height:1.7;color:#bdccda}.detailSkillGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:20px;padding-bottom:85px}.detailSkillGrid article{position:relative;padding:38px;background:#0d3158;border:1px solid rgba(255,255,255,.12)}.detailSkillGrid article>span{position:absolute;right:30px;top:28px;color:#8ba4bb;font:700 12px var(--font-display)}.detailIcon{display:grid;place-items:center;width:52px;height:52px;background:var(--gold);color:var(--navy);margin-bottom:46px}.detailSkillGrid h2{font:650 32px var(--font-display);margin:0 0 16px}.detailSkillGrid p{color:#b8c8d7;line-height:1.7;min-height:80px}.detailSkillGrid article>div:last-child{display:flex;gap:8px;flex-wrap:wrap;margin-top:25px}.detailSkillGrid b{font-size:9px;letter-spacing:.12em;border:1px solid #3d5875;padding:8px 10px;color:#c3d0dc}.detailFooter{display:flex;justify-content:space-between;padding:40px 0;font-weight:800;border-top:1px solid rgba(255,255,255,.15)}.detailFooter a{display:flex;align-items:center;gap:9px}@media(max-width:700px){.detailNav{height:74px}.detailNav .brand strong{display:none}.detailNav>div{gap:15px;font-size:10px}.detailNav>div>a:last-child{display:none}.detailHero{padding:72px 0 60px}.detailLead{font-size:17px}.detailSkillGrid{grid-template-columns:1fr;padding-bottom:65px}.detailFooter{font-size:13px}}`}</style>
    </main>
  );
}
